// <auto-generated />
namespace OpalServices.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changestousersentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestousersentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703021504168_changes to users entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
